config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "localhost"
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  root 'pages#home'

  # resources :users do
    resources :profiles, only: [:index, :show, :edit, :update]
  # end

  resources :conversations, only: [:index, :create, :show, :update, :destroy] do
    resources :messages, only: [:create, :update, :destroy]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wegotsingles</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <header>
	    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
		    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
		    </button>
		    <%= link_to "We Got Singles",  root_path, class: "navbar-brand"%>
		    <div class="collapse navbar-collapse" id="navbarNav">
			    <ul class="nav navbar-nav">
				    <% if user_signed_in?%>
						    <li class="nav-item">
							    <%= link_to "My Messages",  conversations_path, class: "nav-link"%>
						    </li>
						    <li class="nav-item">
							    <%= link_to "My profile",  profile_path(current_user.profile), class: "nav-link"%>
						    </li>
						    <li class="nav-item">
							    <%= link_to "Search",  profiles_path, class: "nav-link"%>
						    </li>
				    <% end  %>
			    </ul>
			    <div class="logout col-md-4 offset-md-4">
				    <% if user_signed_in? %>
						    <p>Signed in as <%= current_user.username %></p>
						    <%= button_to "Logout", destroy_user_session_path, method: :delete,  class: "btn btn-danger"  %>
				    <% end %>
			    </div>
		    </div>
	    </nav>
    </header>

    <main>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
        <%= yield %>
    </main>

    <footer>
      <p><span class="copy-left">&copy;</span> 2016 Creative Commons</p>
    </footer>

  </body>
</html>